[theme]
base = "light"
primaryColor = "#16A085"
backgroundColor = "#FAFAFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A2233"
font = "sans serif"

[logger]
level = "warning"

[client]
showErrorDetails = false

[browser]
gatherUsageStats = false
